import InteractiveBentoGallery from "@/components/ui/interactive-bento-gallery";

const mediaItems = [
  {
    id: 1,
    type: "image",
    title: "Cyberpunk Cityscape",
    desc: "Neon-lit streets, volumetric fog, blade runner aesthetic",
    url: "https://images.unsplash.com/photo-1545486332-9e0999c535b2?w=800&q=80",
    span: "md:col-span-1 md:row-span-3 sm:col-span-1 sm:row-span-2",
  },
  {
    id: 2,
    type: "image",
    title: "Abstract Digital Wave",
    desc: "Flowing sine waves in electric blue and violet",
    url: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&q=80",
    span: "md:col-span-2 md:row-span-2 col-span-1 sm:col-span-2 sm:row-span-2",
  },
  {
    id: 3,
    type: "image",
    title: "Mystical Forest",
    desc: "Ancient trees with glowing roots, foggy night",
    url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
    span: "md:col-span-1 md:row-span-3 sm:col-span-2 sm:row-span-2",
  },
  {
    id: 4,
    type: "image",
    title: "Impressionist Portrait",
    desc: "Soft brushstrokes, warm golden hour light",
    url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80",
    span: "md:col-span-2 md:row-span-2 sm:col-span-1 sm:row-span-2",
  },
  {
    id: 5,
    type: "image",
    title: "Fantasy Mountain Fortress",
    desc: "Epic fortress, storm clouds, concept art style",
    url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    span: "md:col-span-1 md:row-span-3 sm:col-span-1 sm:row-span-2",
  },
  {
    id: 6,
    type: "image",
    title: "Retro Synthwave",
    desc: "Neon pink sky, chrome grid horizon, 80s aesthetic",
    url: "https://images.unsplash.com/photo-1518655048521-f130df041f66?w=800&q=80",
    span: "md:col-span-2 md:row-span-2 sm:col-span-1 sm:row-span-2",
  },
  {
    id: 7,
    type: "image",
    title: "Tropical Beach",
    desc: "Sunny paradise, crystal clear water, golden sand",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    span: "md:col-span-1 md:row-span-3 sm:col-span-1 sm:row-span-2",
  },
];

export default function GalleryPage() {
  return (
    <main className="flex-1 bg-white dark:bg-[#111111] py-12 transition-colors">
      <InteractiveBentoGallery
        mediaItems={mediaItems}
        title="Community Gallery"
        description="Explore prompts generated by the PromptLens community. Drag to reorder, click to preview."
      />
    </main>
  );
}
