import Link from "next/link";

const GALLERY_ITEMS = [
  {
    id: "1",
    title: "Cyberpunk cityscape at night",
    tags: ["Architecture", "Sci-Fi"],
    prompt:
      "A towering neon-lit cyberpunk city at midnight, rain-slicked streets reflecting holographic advertisements, cinematic composition, volumetric fog, blade runner aesthetic, ultra-detailed, 8k, photorealistic",
  },
  {
    id: "2",
    title: "Impressionist portrait",
    tags: ["Portrait", "Art"],
    prompt:
      "Impressionist oil painting portrait, soft brushstrokes, warm golden hour light, Monet style, muted earthy tones, expressive face, painterly texture, museum quality",
  },
  {
    id: "3",
    title: "Abstract digital wave",
    tags: ["Abstract", "Digital"],
    prompt:
      "Abstract generative art, flowing sine waves in electric blue and violet, dark background, mathematical precision, glowing edges, data visualization aesthetic, high contrast",
  },
  {
    id: "4",
    title: "Fantasy mountain fortress",
    tags: ["Architecture", "Fantasy"],
    prompt:
      "Epic fantasy fortress built into a jagged mountain peak, surrounded by storm clouds, dramatic lighting, concept art style, cinematic wide angle, detailed stone architecture",
  },
  {
    id: "5",
    title: "Ethereal forest spirit",
    tags: ["Nature", "Fantasy"],
    prompt:
      "Mystical forest spirit glowing with bioluminescent light, ancient trees with glowing roots, foggy night, studio ghibli style, soft pastel colors, hand-painted look",
  },
  {
    id: "6",
    title: "Retro synthwave sunset",
    tags: ["Landscape", "Retro"],
    prompt:
      "Retro synthwave sunset over the ocean, neon pink and purple sky, chrome grid horizon, 80s aesthetic, palm tree silhouettes, retrowave, outrun style, highly stylized",
  },
];

const ALL_TAGS = [
  "All",
  "Architecture",
  "Portrait",
  "Abstract",
  "Nature",
  "Landscape",
  "Sci-Fi",
  "Fantasy",
  "Retro",
  "Art",
  "Digital",
];

export default function GalleryPage() {
  return (
    <main className="flex-1 bg-neutral-950 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold text-white mb-4">Gallery</h1>
          <p className="text-neutral-400 text-xl max-w-lg mx-auto">
            Explore prompts generated by the PromptLens community.
          </p>
        </div>

        {/* Tag filter */}
        <div className="flex flex-wrap gap-2 justify-center mb-10">
          {ALL_TAGS.map((tag) => (
            <span
              key={tag}
              className={`px-4 py-1.5 rounded-full text-sm transition-colors cursor-pointer ${
                tag === "All"
                  ? "bg-indigo-600 text-white"
                  : "bg-neutral-900 border border-neutral-800 text-neutral-400 hover:text-white hover:border-neutral-600"
              }`}
            >
              {tag}
            </span>
          ))}
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {GALLERY_ITEMS.map((item) => (
            <Link
              key={item.id}
              href={`/gallery/${item.id}`}
              className="bg-neutral-900 border border-neutral-800 rounded-2xl overflow-hidden hover:border-indigo-800/60 transition-colors group"
            >
              {/* Placeholder image area */}
              <div className="aspect-video bg-gradient-to-br from-neutral-800 to-neutral-900 flex items-center justify-center">
                <svg
                  className="w-8 h-8 text-neutral-700"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={1}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M2.25 15.75l5.159-5.159a2.25 2.25 0 013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909M3 3.75h18M3 20.25h18M12 12a2.25 2.25 0 100-4.5 2.25 2.25 0 000 4.5z"
                  />
                </svg>
              </div>
              <div className="p-5">
                <div className="flex flex-wrap gap-1.5 mb-3">
                  {item.tags.map((tag) => (
                    <span
                      key={tag}
                      className="text-xs bg-indigo-950/50 text-indigo-300 border border-indigo-800/30 px-2 py-0.5 rounded-full"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
                <h3 className="text-white font-semibold text-sm mb-2 group-hover:text-indigo-300 transition-colors">
                  {item.title}
                </h3>
                <p className="text-neutral-500 text-xs leading-relaxed line-clamp-2">{item.prompt}</p>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </main>
  );
}
