export default function TermsPage() {
  return (
    <main className="flex-1 bg-neutral-950 py-20 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <div className="mb-12">
          <h1 className="text-4xl font-bold text-white mb-3">Terms of Service</h1>
          <p className="text-neutral-500 text-sm">Last updated: May 30, 2026</p>
        </div>

        <div className="space-y-10 text-sm">
          {[
            {
              id: "acceptance",
              title: "1. Acceptance",
              content:
                "By accessing or using PromptLens, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.",
            },
            {
              id: "permitted-use",
              title: "2. Permitted Use",
              content:
                "You may use PromptLens for personal and commercial creative projects. You must not upload images you do not have the right to use, attempt to circumvent rate limits or access restrictions, or use the service in any way that violates applicable laws or these terms.",
            },
            {
              id: "intellectual-property",
              title: "3. Intellectual Property",
              content:
                "Prompts generated by PromptLens are yours to use freely. PromptLens retains no ownership over generated content. The PromptLens name, logo, and software remain the property of their respective owners and may not be reproduced without permission.",
            },
            {
              id: "prohibited-content",
              title: "4. Prohibited Content",
              content:
                "You may not upload images containing illegal content, content that violates the intellectual property rights or privacy of others, or content intended to generate harmful, harassing, abusive, or discriminatory outputs.",
            },
            {
              id: "disclaimer",
              title: "5. Disclaimer",
              content:
                "PromptLens is provided 'as is' without warranty of any kind, express or implied. We do not guarantee the accuracy, completeness, or fitness for a particular purpose of generated prompts. Use the service at your own discretion.",
            },
            {
              id: "limitation-of-liability",
              title: "6. Limitation of Liability",
              content:
                "PromptLens shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service, to the maximum extent permitted by applicable law.",
            },
            {
              id: "changes",
              title: "7. Changes to Terms",
              content:
                "We may update these terms from time to time. We will notify registered users of material changes by email. Continued use of the service after changes constitutes acceptance of the updated terms.",
            },
            {
              id: "contact",
              title: "8. Contact",
              content:
                "For terms-related inquiries, please contact us at legal@promptlens.ai.",
            },
          ].map((section) => (
            <section key={section.id} id={section.id}>
              <h2 className="text-white font-semibold text-base mb-3">{section.title}</h2>
              <p className="text-neutral-400 leading-relaxed">{section.content}</p>
            </section>
          ))}
        </div>
      </div>
    </main>
  );
}
